--------------------------------------------------------
--  File created - Wednesday-December-30-2020   
--------------------------------------------------------
DROP TABLE "ANOTHERONE"."ABONNEMENTS" cascade constraints;
DROP TABLE "ANOTHERONE"."ACCOUNTS" cascade constraints;
DROP TABLE "ANOTHERONE"."EMPLOYEE" cascade constraints;
DROP TABLE "ANOTHERONE"."EVENTS" cascade constraints;
DROP TABLE "ANOTHERONE"."MOVIES" cascade constraints;
DROP TABLE "ANOTHERONE"."PARKING" cascade constraints;
DROP TABLE "ANOTHERONE"."PRODUCTS" cascade constraints;
DROP TABLE "ANOTHERONE"."PROFIL" cascade constraints;
DROP TABLE "ANOTHERONE"."PVENTES" cascade constraints;
DROP TABLE "ANOTHERONE"."RESERVATION" cascade constraints;
DROP TABLE "ANOTHERONE"."ROOMS" cascade constraints;
DROP TABLE "ANOTHERONE"."SUBSCRIBERS" cascade constraints;
--------------------------------------------------------
--  DDL for Table ABONNEMENTS
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."ABONNEMENTS" 
   (	"ID" NUMBER, 
	"DATES" VARCHAR2(30 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"POINTS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."ACCOUNTS" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"OWNERID" NUMBER, 
	"SUPERUSER" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."EMPLOYEE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTS
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."EVENTS" 
   (	"ID" NUMBER, 
	"ROOMID" NUMBER, 
	"EVNAME" VARCHAR2(20 BYTE), 
	"EVTYPE" VARCHAR2(20 BYTE), 
	"TIME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MOVIES
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."MOVIES" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"LENGTH" VARCHAR2(20 BYTE), 
	"LANGUAGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PARKING
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."PARKING" 
   (	"ID" NUMBER, 
	"SPOT" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(20 BYTE), 
	"CO" VARCHAR2(20 BYTE), 
	"LICENSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."PRODUCTS" 
   (	"ID" NUMBER, 
	"PNAME" VARCHAR2(20 BYTE), 
	"PTYPE" VARCHAR2(20 BYTE), 
	"PQUANTITY" VARCHAR2(20 BYTE), 
	"PDATE" VARCHAR2(20 BYTE), 
	"PVENTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROFIL
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."PROFIL" 
   (	"ID" NUMBER, 
	"PROFILE" VARCHAR2(20 BYTE), 
	"POST" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PVENTES
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."PVENTES" 
   (	"PVID" NUMBER, 
	"ROOM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."RESERVATION" 
   (	"ID" NUMBER, 
	"IDFILM" NUMBER, 
	"IDEVENT" NUMBER, 
	"NPLACES" VARCHAR2(20 BYTE), 
	"DATERES" VARCHAR2(20 BYTE), 
	"IDSUBSCRIBER" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ROOMS
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."ROOMS" 
   (	"ID" NUMBER, 
	"CHAIRSIZE" VARCHAR2(20 BYTE), 
	"CHAIRCOUNT" VARCHAR2(20 BYTE), 
	"CHAIRQUALITY" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SUBSCRIBERS
--------------------------------------------------------

  CREATE TABLE "ANOTHERONE"."SUBSCRIBERS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(20 BYTE), 
	"IDABONNEMENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ANOTHERONE.ABONNEMENTS
SET DEFINE OFF;
REM INSERTING into ANOTHERONE.ACCOUNTS
SET DEFINE OFF;
Insert into ANOTHERONE.ACCOUNTS (ID,USERNAME,PASSWORD,OWNERID,SUPERUSER) values (1,'admin','admin',100,1);
Insert into ANOTHERONE.ACCOUNTS (ID,USERNAME,PASSWORD,OWNERID,SUPERUSER) values (2,'kk','kk',22,0);
REM INSERTING into ANOTHERONE.EMPLOYEE
SET DEFINE OFF;
REM INSERTING into ANOTHERONE.EVENTS
SET DEFINE OFF;
Insert into ANOTHERONE.EVENTS (ID,ROOMID,EVNAME,EVTYPE,TIME) values (2,125,'party','disco','14-DEC-20 05.30.10.000000000 PM');
REM INSERTING into ANOTHERONE.MOVIES
SET DEFINE OFF;
REM INSERTING into ANOTHERONE.PARKING
SET DEFINE OFF;
Insert into ANOTHERONE.PARKING (ID,SPOT,STATE,CO,LICENSE) values (1,'Spot 1','FREE','-','FREE');
Insert into ANOTHERONE.PARKING (ID,SPOT,STATE,CO,LICENSE) values (2,'Spot 2','TAKEN','Yasine','150TN6574');
Insert into ANOTHERONE.PARKING (ID,SPOT,STATE,CO,LICENSE) values (3,'Spot 3','FREE','-','FREE');
Insert into ANOTHERONE.PARKING (ID,SPOT,STATE,CO,LICENSE) values (4,'Spot 4','TAKEN','yasmine','150TN2400');
REM INSERTING into ANOTHERONE.PRODUCTS
SET DEFINE OFF;
Insert into ANOTHERONE.PRODUCTS (ID,PNAME,PTYPE,PQUANTITY,PDATE,PVENTE) values (3,'Snickers','food','2447','24/02/2047','2');
Insert into ANOTHERONE.PRODUCTS (ID,PNAME,PTYPE,PQUANTITY,PDATE,PVENTE) values (1,'popcorn','food','2000','12/05/2020','1');
Insert into ANOTHERONE.PRODUCTS (ID,PNAME,PTYPE,PQUANTITY,PDATE,PVENTE) values (2,'chips','food','1325','31/07/2020','1');
REM INSERTING into ANOTHERONE.PROFIL
SET DEFINE OFF;
REM INSERTING into ANOTHERONE.PVENTES
SET DEFINE OFF;
Insert into ANOTHERONE.PVENTES (PVID,ROOM) values (1,'Room 1');
Insert into ANOTHERONE.PVENTES (PVID,ROOM) values (2,'Room 2');
REM INSERTING into ANOTHERONE.RESERVATION
SET DEFINE OFF;
Insert into ANOTHERONE.RESERVATION (ID,IDFILM,IDEVENT,NPLACES,DATERES,IDSUBSCRIBER) values (1,15,14,'250','12/11/22',null);
Insert into ANOTHERONE.RESERVATION (ID,IDFILM,IDEVENT,NPLACES,DATERES,IDSUBSCRIBER) values (3,22,27,'142','15/11/22',null);
Insert into ANOTHERONE.RESERVATION (ID,IDFILM,IDEVENT,NPLACES,DATERES,IDSUBSCRIBER) values (2,14,16,'214','12/22/20',null);
Insert into ANOTHERONE.RESERVATION (ID,IDFILM,IDEVENT,NPLACES,DATERES,IDSUBSCRIBER) values (4,0,0,null,null,null);
Insert into ANOTHERONE.RESERVATION (ID,IDFILM,IDEVENT,NPLACES,DATERES,IDSUBSCRIBER) values (5,0,0,null,'v',null);
Insert into ANOTHERONE.RESERVATION (ID,IDFILM,IDEVENT,NPLACES,DATERES,IDSUBSCRIBER) values (6,0,0,null,'v',null);
Insert into ANOTHERONE.RESERVATION (ID,IDFILM,IDEVENT,NPLACES,DATERES,IDSUBSCRIBER) values (7,0,0,null,'v',null);
REM INSERTING into ANOTHERONE.ROOMS
SET DEFINE OFF;
Insert into ANOTHERONE.ROOMS (ID,CHAIRSIZE,CHAIRCOUNT,CHAIRQUALITY) values (1,'large','125','Good');
REM INSERTING into ANOTHERONE.SUBSCRIBERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index ABONNEMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."ABONNEMENTS_PK" ON "ANOTHERONE"."ABONNEMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCOUNTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."ACCOUNTS_PK" ON "ANOTHERONE"."ACCOUNTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."EMPLOYEE_PK" ON "ANOTHERONE"."EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."EVENTS_PK" ON "ANOTHERONE"."EVENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MOVIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."MOVIES_PK" ON "ANOTHERONE"."MOVIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PARKING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."PARKING_PK" ON "ANOTHERONE"."PARKING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PVENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."PVENTE_PK" ON "ANOTHERONE"."PRODUCTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROFIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."PROFIL_PK" ON "ANOTHERONE"."PROFIL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PVENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."PVENTES_PK" ON "ANOTHERONE"."PVENTES" ("PVID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."RESERVATION_PK" ON "ANOTHERONE"."RESERVATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ROOMS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."ROOMS_PK" ON "ANOTHERONE"."ROOMS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ANOTHERONE"."TABLE1_PK" ON "ANOTHERONE"."SUBSCRIBERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ABONNEMENTS
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."ABONNEMENTS" ADD CONSTRAINT "ABONNEMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."ABONNEMENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."ACCOUNTS" MODIFY ("OWNERID" NOT NULL ENABLE);
  ALTER TABLE "ANOTHERONE"."ACCOUNTS" ADD CONSTRAINT "ACCOUNTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."ACCOUNTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."EVENTS" ADD CONSTRAINT "EVENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."EVENTS" MODIFY ("ROOMID" NOT NULL ENABLE);
  ALTER TABLE "ANOTHERONE"."EVENTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MOVIES
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."MOVIES" ADD CONSTRAINT "MOVIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."MOVIES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PARKING
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."PARKING" ADD CONSTRAINT "PARKING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."PARKING" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."PRODUCTS" ADD CONSTRAINT "PVENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."PRODUCTS" MODIFY ("PVENTE" NOT NULL ENABLE);
  ALTER TABLE "ANOTHERONE"."PRODUCTS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROFIL
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."PROFIL" ADD CONSTRAINT "PROFIL_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."PROFIL" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PVENTES
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."PVENTES" ADD CONSTRAINT "PVENTES_PK" PRIMARY KEY ("PVID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."PVENTES" MODIFY ("PVID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."RESERVATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROOMS
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."ROOMS" ADD CONSTRAINT "ROOMS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."ROOMS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBSCRIBERS
--------------------------------------------------------

  ALTER TABLE "ANOTHERONE"."SUBSCRIBERS" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ANOTHERONE"."SUBSCRIBERS" MODIFY ("ID" NOT NULL ENABLE);
